import Head from "next/head";
import Message from "../components/message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  //Create a state with all the posts
  const [collectionData, setCollectionData] = useState([]);

  const fetchCollectionData = () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
  
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map((doc) => doc.data());
      setCollectionData(data);
    });
  
    return unsubscribe;
  };
  

  useEffect(() => {
    const unsubscribe = fetchCollectionData();
  
    return () => {
      unsubscribe();
    };
  }, []);
  console.log(collectionData);


  return (
    <div>
      <Head>
        <title>Creative Minds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {collectionData.map((post) => (
          <Message key={post.id} {...post}>
          </Message>
        ))}
      </div>
    </div>
  );
}
